# Log4j Properties File

log4j.logger.IDFC_SINGLE_TFN_CVP.ERROR.com.servionsfw.framework.loader.common.ApplicationStartLoader=ERROR, XML_ERRORFILE
log4j.logger.IDFC_SINGLE_TFN_CVP.INFO.com.servionsfw.framework.loader.common.ApplicationStartLoader=DEBUG, XML_DEBUGFILE

log4j.logger.com.servionsfw.framework.report.bc=DEBUG,REPORT_ORGANISER
log4j.logger.com.servionsfw.framework.report.common=DEBUG,REPORT_INITIALIZER
log4j.logger.com.servionsfw.framework.report.resourcemanager.bc=DEBUG,REPORT_MANAGER
log4j.logger.com.servionsfw.framework.report.listener=DEBUG,REPORT_MANAGER
log4j.logger.com.servionsfw.framework.report.sharedmemory.bc=DEBUG,SHARED_MEMORY
log4j.logger.IDFC_SINGLE_TFN_CVP.com.servionsfw.common.ReportingCallEnd=DEBUG,CUSTOM_LOGGER
log4j.additivity.XML_ERRORFILE=false
log4j.additivity.XML_DEBUGFILE=false

#### Report Logger - Call related Error information is available at this location ###

log4j.appender.XML_ERRORFILE=org.apache.log4j.RollingFileAppender
log4j.appender.XML_ERRORFILE.File=C:/servion/Framework/IDFC_SINGLE_TFN_CVP/logs/error.log
log4j.appender.XML_ERRORFILE.Threshold=ERROR
log4j.appender.XML_ERRORFILE.Append=false
log4j.appender.XML_ERRORFILE.MaxFileSize=5000KB
log4j.appender.XML_ERRORFILE.MaxBackupIndex=10
log4j.appender.XML_ERRORFILE.layout=org.apache.log4j.PatternLayout
log4j.appender.XML_ERRORFILE.layout.ConversionPattern=[%d{yyyy-MMM-dd HH:mm:ss}] - %m%n

### Report Logger - Call related Debug information is available at this location ###

log4j.appender.XML_DEBUGFILE=org.apache.log4j.RollingFileAppender
log4j.appender.XML_DEBUGFILE.File=C:/servion/Framework/IDFC_SINGLE_TFN_CVP/logs/debug.log
log4j.appender.XML_DEBUGFILE.Threshold=DEBUG
log4j.appender.XML_DEBUGFILE.Append=false
log4j.appender.XML_DEBUGFILE.MaxFileSize=5000KB
log4j.appender.XML_DEBUGFILE.MaxBackupIndex=10
log4j.appender.XML_DEBUGFILE.layout=org.apache.log4j.PatternLayout
log4j.appender.XML_DEBUGFILE.layout.ConversionPattern=[%d{yyyy-MMM-dd HH:mm:ss}] - %m%n

log4j.additivity.REPORT_ORGANISER=false
log4j.appender.REPORT_ORGANISER=org.apache.log4j.RollingFileAppender 
log4j.appender.REPORT_ORGANISER.File=C:/servion/Framework/IDFC_SINGLE_TFN_CVP/logs/report/reportOrganizer.log
log4j.appender.REPORT_ORGANISER.Threshold=DEBUG
log4j.appender.REPORT_ORGANISER.Append=true
log4j.appender.REPORT_ORGANISER.MaxFileSize=5000KB
log4j.appender.REPORT_ORGANISER.MaxBackupIndex=10
log4j.appender.REPORT_ORGANISER.layout=org.apache.log4j.PatternLayout
log4j.appender.REPORT_ORGANISER.layout.ConversionPattern=[%d{yyyy-MMM-dd HH:mm:ss},%6.6r]%-5p %6.10r[%t]%x(%F:%L) - %m%n

log4j.additivity.REPORT_INITIALIZER=false
log4j.appender.REPORT_INITIALIZER=org.apache.log4j.RollingFileAppender 
log4j.appender.REPORT_INITIALIZER.File=C:/servion/Framework/IDFC_SINGLE_TFN_CVP/logs/report/reportInitializer.log
log4j.appender.REPORT_INITIALIZER.Threshold=DEBUG
log4j.appender.REPORT_INITIALIZER.Append=true
log4j.appender.REPORT_INITIALIZER.MaxFileSize=5000KB
log4j.appender.REPORT_INITIALIZER.MaxBackupIndex=10
log4j.appender.REPORT_INITIALIZER.layout=org.apache.log4j.PatternLayout
log4j.appender.REPORT_INITIALIZER.layout.ConversionPattern=[%d{yyyy-MMM-dd HH:mm:ss},%6.6r]%-5p %6.10r[%t]%x(%F:%L) - %m%n

log4j.additivity.REPORT_MANAGER=false
log4j.appender.REPORT_MANAGER=org.apache.log4j.RollingFileAppender 
log4j.appender.REPORT_MANAGER.File=C:/servion/Framework/IDFC_SINGLE_TFN_CVP/logs/report/reportManager.log
log4j.appender.REPORT_MANAGER.Threshold=DEBUG
log4j.appender.REPORT_MANAGER.Append=true
log4j.appender.REPORT_MANAGER.MaxFileSize=5000KB
log4j.appender.REPORT_MANAGER.MaxBackupIndex=10
log4j.appender.REPORT_MANAGER.layout=org.apache.log4j.PatternLayout
log4j.appender.REPORT_MANAGER.layout.ConversionPattern=[%d{yyyy-MMM-dd HH:mm:ss},%6.6r]%-5p %6.10r[%t]%x(%F:%L) - %m%n

log4j.additivity.SHARED_MEMORY=false
log4j.appender.SHARED_MEMORY=org.apache.log4j.RollingFileAppender 
log4j.appender.SHARED_MEMORY.File=C:/servion/Framework/IDFC_SINGLE_TFN_CVP/logs/report/sharedMemory.log
log4j.appender.SHARED_MEMORY.Threshold=DEBUG
log4j.appender.SHARED_MEMORY.Append=true
log4j.appender.SHARED_MEMORY.MaxFileSize=5000KB
log4j.appender.SHARED_MEMORY.MaxBackupIndex=10
log4j.appender.SHARED_MEMORY.layout=org.apache.log4j.PatternLayout
log4j.appender.SHARED_MEMORY.layout.ConversionPattern=[%d{yyyy-MMM-dd HH:mm:ss},%6.6r]%-5p %6.10r[%t]%x(%F:%L) - %m%n

log4j.additivity.CUSTOM_LOGGER=false
log4j.appender.CUSTOM_LOGGER=org.apache.log4j.RollingFileAppender 
log4j.appender.CUSTOM_LOGGER.File=C:/servion/Framework/IDFC_SINGLE_TFN_CVP/logs/report/customLogger.log
log4j.appender.CUSTOM_LOGGER.Threshold=DEBUG
log4j.appender.CUSTOM_LOGGER.Append=true
log4j.appender.CUSTOM_LOGGER.MaxFileSize=5000KB
log4j.appender.CUSTOM_LOGGER.MaxBackupIndex=10
log4j.appender.CUSTOM_LOGGER.layout=org.apache.log4j.PatternLayout
log4j.appender.CUSTOM_LOGGER.layout.ConversionPattern=[%d{yyyy-MMM-dd HH:mm:ss},%6.6r]%-5p %6.10r[%t]%x(%F:%L) - %m%n